name: Manual Trigger

on:
  workflow_dispatch:
    inputs:
      ログレベル:
        required: true
        description: ログレベル
        default: warning
      タグ:
        description: タグ

jobs:
  printInputs:
    runs-on: ubuntu-latest

    steps:
    - run: |
        echo "Log level: ${{ github.event.inputs.logLevel }}"
        echo "Tags: ${{ github.event.inputs.tags }}" 
